"""added user_progress

Revision ID: a15c75b1e8fb
Revises: 
Create Date: 2025-06-10 17:31:08.501319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a15c75b1e8fb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_progress', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user_progress', ['user_progress'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_progress')

    # ### end Alembic commands ###
