"""initial migration

Revision ID: 601dad3cb181
Revises: 
Create Date: 2025-06-10 17:37:55.464923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '601dad3cb181'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('routine',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('routine_name', sa.String(), nullable=True),
    sa.Column('routine_level', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test__workouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workout_name', sa.String(), nullable=False),
    sa.Column('body_part', sa.String(), nullable=True),
    sa.Column('muscle_targeted', sa.String(), nullable=True),
    sa.Column('workout_link', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workout_name', sa.String(), nullable=False),
    sa.Column('body_part', sa.String(), nullable=True),
    sa.Column('muscle_targeted', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workout_name', sa.String(), nullable=False),
    sa.Column('body_part', sa.String(), nullable=True),
    sa.Column('muscle_targeted', sa.String(), nullable=True),
    sa.Column('workout_link', sa.String(), nullable=True),
    sa.Column('workout_pic_link', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('day_of_routine',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workout_day_name', sa.String(), nullable=True),
    sa.Column('w1', sa.String(), nullable=True),
    sa.Column('w2', sa.String(), nullable=True),
    sa.Column('w3', sa.String(), nullable=True),
    sa.Column('w4', sa.String(), nullable=True),
    sa.Column('w5', sa.String(), nullable=True),
    sa.Column('w6', sa.String(), nullable=True),
    sa.Column('w7', sa.String(), nullable=True),
    sa.Column('w8', sa.String(), nullable=True),
    sa.Column('routine_name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['routine_name'], ['routine.routine_name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test__day_of_routine',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workout_day_name', sa.String(), nullable=True),
    sa.Column('w1', sa.String(), nullable=True),
    sa.Column('w2', sa.String(), nullable=True),
    sa.Column('w3', sa.String(), nullable=True),
    sa.Column('w4', sa.String(), nullable=True),
    sa.Column('w5', sa.String(), nullable=True),
    sa.Column('w6', sa.String(), nullable=True),
    sa.Column('w7', sa.String(), nullable=True),
    sa.Column('w8', sa.String(), nullable=True),
    sa.Column('routine_name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['routine_name'], ['routine.routine_name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('goal', sa.String(length=20), nullable=True),
    sa.Column('beginning_day_id', sa.Integer(), nullable=True),
    sa.Column('current_day_id', sa.Integer(), nullable=True),
    sa.Column('routine_change_date', sa.Date(), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('level', sa.String(), nullable=False),
    sa.Column('days_logged_in', sa.Integer(), nullable=True),
    sa.Column('user_routine', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_routine'], ['routine.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('goal', sa.String(length=20), nullable=True),
    sa.Column('beginning_day_id', sa.Integer(), nullable=True),
    sa.Column('current_day_id', sa.Integer(), nullable=True),
    sa.Column('routine_change_date', sa.Date(), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('level', sa.String(), nullable=True),
    sa.Column('days_logged_in', sa.Integer(), nullable=True),
    sa.Column('user_routine', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_routine'], ['routine.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('user_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workout_done', sa.String(), nullable=True),
    sa.Column('sets', sa.Integer(), nullable=True),
    sa.Column('reps', sa.Integer(), nullable=True),
    sa.Column('weight_lifted', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_progress')
    op.drop_table('users')
    op.drop_table('test_users')
    op.drop_table('test__day_of_routine')
    op.drop_table('day_of_routine')
    op.drop_table('workouts')
    op.drop_table('test_data')
    op.drop_table('test__workouts')
    op.drop_table('routine')
    # ### end Alembic commands ###
